let a = 23;
let b = 9;
let soma = a+b;
console.log('O resultado de ' + a + '+' + b + ' é igual a: ', soma);
let sub = a - b;
console.log('O resultado de ' + a + '-' + b + ' é igual a: ', sub);
let mult = a * b;
console.log('O resultado de ' + a + '*' + b + ' é igual a: ', mult);
let div = a/b;
console.log('O resultado de ' + a + '/' + b + ' é igual a: ', div);
let mod = a%b;
console.log('O resto da divisão de ' + a + '/' + b + ' é igual a: ', mod);